import { Company } from "./types";

function slug(name: string, year: number): string {
  return `${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-+$/, "")}-${year}`;
}

export const companies: Company[] = [
  // ===== 2005 =====
  {
    id: slug("Sourcefire", 2005),
    name: "Sourcefire",
    year: 2005,
    winner: true,
    description:
      "Network security and intrusion detection/prevention systems (IDS/IPS); creator of the Snort open-source IDS.",
    status: "acquired",
    category: "Network Security",
    founded: 2001,
    acquisitionDetails: "Acquired by Cisco Systems in 2013 for $2.7B",
    notes: "IPO in 2007 raising $71M. First-ever Innovation Sandbox winner (then called 'Innovation Station').",
    lessonLearned:
      "Open-source community building (Snort) created massive adoption that translated into commercial success. Lesson: give away the detection engine, sell the management platform.",
  },

  // ===== 2006 =====
  {
    id: slug("Imperva", 2006),
    name: "Imperva",
    year: 2006,
    winner: true,
    description:
      "Web application firewall (WAF) and database security provider.",
    status: "acquired",
    category: "Application Security",
    founded: 2002,
    acquisitionDetails: "Acquired by Thales Group in 2019 for $3.6B (after IPO in 2011, went private with Thoma Bravo in 2018)",
    ipoDetails: "IPO in 2011 raising $90M",
    lessonLearned:
      "Pioneered WAF market at scale. Lesson: creating a new security category (database activity monitoring + WAF) can yield massive returns if timing matches regulatory pressure.",
  },
  {
    id: slug("Elemental Security", 2006),
    name: "Elemental Security",
    year: 2006,
    winner: false,
    description:
      "Security policy management and compliance platform.",
    status: "acquired",
    category: "Security Operations",
    acquisitionDetails: "Acquired by ArcSight in 2009",
    notes: "Some sources cite Elemental Security as co-winner in 2006.",
  },

  // ===== 2007 =====
  {
    id: slug("Yoggie Security Systems", 2007),
    name: "Yoggie Security Systems",
    year: 2007,
    winner: true,
    description:
      "Hardware-based personal security device providing endpoint protection via a dedicated security mini-computer.",
    status: "shutdown",
    category: "Endpoint Security",
    founded: 2005,
    acquisitionDetails: "Acquired by CUPP Computing in 2011 (acqui-hire)",
    shutdownDetails: "Technology was ahead of its time; hardware security appliances for endpoints didn't gain mainstream adoption.",
    lessonLearned:
      "Hardware-based endpoint security was too niche and expensive for mainstream adoption. Lesson: if the form factor doesn't match the market's buying behavior, even innovative tech struggles.",
  },

  // ===== 2009 =====
  {
    id: slug("AlertEnterprise", 2009),
    name: "AlertEnterprise",
    year: 2009,
    winner: true,
    description:
      "Converged cyber-physical security and access governance platform.",
    status: "active",
    category: "Identity & Access",
    founded: 2007,
    lessonLearned:
      "Bridging IT and physical security was visionary but slow to adopt. Now thriving as IT/OT convergence becomes mainstream.",
  },
  {
    id: slug("Yubico", 2009),
    name: "Yubico",
    year: 2009,
    winner: false,
    description:
      "Hardware authentication security keys (YubiKey) for strong two-factor authentication.",
    status: "ipo",
    category: "Identity & Access",
    founded: 2007,
    ipoDetails: "Went public via direct listing on Nasdaq Stockholm in 2023",
    lessonLearned:
      "Didn't win the Sandbox but became one of the most successful finalists ever. Lesson: hardware-based auth with open standards (FIDO/U2F) can create a durable moat.",
  },
  {
    id: slug("Trusteer", 2009),
    name: "Trusteer",
    year: 2009,
    winner: false,
    description:
      "Online banking fraud prevention and endpoint protection against financial malware.",
    status: "acquired",
    category: "Threat Detection",
    founded: 2006,
    acquisitionDetails: "Acquired by IBM in 2013 for ~$1B",
  },
  {
    id: slug("Prevx", 2009),
    name: "Prevx",
    year: 2009,
    winner: false,
    description: "Cloud-based anti-malware and endpoint protection.",
    status: "acquired",
    category: "Endpoint Security",
    founded: 2003,
    acquisitionDetails: "Acquired by Webroot in 2010",
  },
  {
    id: slug("NetWitness", 2009),
    name: "NetWitness",
    year: 2009,
    winner: false,
    description:
      "Network forensics and security analytics platform for real-time network monitoring.",
    status: "acquired",
    category: "Network Security",
    founded: 2006,
    acquisitionDetails: "Acquired by EMC/RSA in 2011; now part of RSA NetWitness",
  },
  {
    id: slug("Purewire", 2009),
    name: "Purewire",
    year: 2009,
    winner: false,
    description: "Cloud-based web security gateway.",
    status: "acquired",
    category: "Network Security",
    founded: 2007,
    acquisitionDetails: "Acquired by Barracuda Networks in 2009",
  },
  {
    id: slug("Guardium", 2009),
    name: "Guardium",
    year: 2009,
    winner: false,
    description: "Database security and activity monitoring.",
    status: "acquired",
    category: "Data Security",
    founded: 2002,
    acquisitionDetails: "Acquired by IBM in 2009 for ~$225M",
  },
  {
    id: slug("Catbird", 2009),
    name: "Catbird",
    year: 2009,
    winner: false,
    description:
      "Virtualization and cloud infrastructure security monitoring.",
    status: "acquired",
    category: "Cloud Security",
    acquisitionDetails: "Acquired by ServiceMesh (now CSC) around 2013",
  },
  {
    id: slug("Palo Alto Networks", 2009),
    name: "Palo Alto Networks",
    year: 2009,
    winner: false,
    description:
      "Next-generation firewall platform with application-aware traffic inspection.",
    status: "ipo",
    category: "Network Security",
    founded: 2005,
    ipoDetails: "IPO in 2012; market cap over $100B as of 2025",
    lessonLearned:
      "The biggest success story among all Innovation Sandbox finalists. Didn't need to win the contest. Lesson: product-market fit in next-gen firewalls created a generational company.",
  },
  {
    id: slug("Silver Tail Systems", 2009),
    name: "Silver Tail Systems",
    year: 2009,
    winner: false,
    description:
      "Web session intelligence and fraud detection via behavioral analysis.",
    status: "acquired",
    category: "Threat Detection",
    founded: 2008,
    acquisitionDetails: "Acquired by EMC in 2012",
  },

  // ===== 2010 =====
  {
    id: slug("Altor Networks", 2010),
    name: "Altor Networks",
    year: 2010,
    winner: true,
    description:
      "Virtual network firewall for virtualized data centers.",
    status: "acquired",
    category: "Cloud Security",
    founded: 2007,
    acquisitionDetails: "Acquired by Juniper Networks in 2010",
    lessonLearned:
      "Quick acquisition validated the virtual firewall concept. Lesson: in a land grab moment, get acquired fast or get outspent.",
  },
  {
    id: slug("Catbird-2010", 2010),
    name: "Catbird",
    year: 2010,
    winner: false,
    description: "Security compliance and monitoring for virtual and cloud environments.",
    status: "acquired",
    category: "Cloud Security",
    acquisitionDetails: "Acquired by ServiceMesh (later CSC/DXC Technology)",
  },
  {
    id: slug("Incapsula", 2010),
    name: "Incapsula",
    year: 2010,
    winner: false,
    description: "Cloud-based web application security and CDN service.",
    status: "acquired",
    category: "Application Security",
    founded: 2009,
    acquisitionDetails: "Acquired by Imperva in 2014; integrated into Imperva's cloud WAF",
    lessonLearned:
      "Cloud WAF pioneer eventually absorbed by 2006 ISB winner Imperva. The Innovation Sandbox ecosystem feeds itself.",
  },
  {
    id: slug("KiduSema", 2010),
    name: "KiduSema",
    year: 2010,
    winner: false,
    description: "IT risk management and security posture monitoring.",
    status: "shutdown",
    category: "Security Operations",
    shutdownDetails: "Company appears to have ceased operations; limited public information available.",
  },
  {
    id: slug("Navaho Systems", 2010),
    name: "Navaho Systems",
    year: 2010,
    winner: false,
    description: "Mobile security and device management.",
    status: "shutdown",
    category: "Endpoint Security",
    shutdownDetails: "Company no longer operational.",
  },

  // ===== 2011 =====
  {
    id: slug("Invincea", 2011),
    name: "Invincea",
    year: 2011,
    winner: true,
    description:
      "Advanced endpoint protection using application containment and machine learning to prevent malware execution.",
    status: "acquired",
    category: "Endpoint Security",
    founded: 2009,
    acquisitionDetails: "Acquired by Sophos in 2017",
    notes: "Raised $45.5M from five investors.",
    lessonLearned:
      "Early ML-based endpoint protection. Acquired by Sophos rather than competing as standalone. Lesson: deep tech in endpoint security often leads to acquisition by platform vendors.",
  },
  {
    id: slug("Bromium", 2011),
    name: "Bromium",
    year: 2011,
    winner: false,
    description:
      "Micro-virtualization technology to isolate threats at the endpoint.",
    status: "acquired",
    category: "Endpoint Security",
    founded: 2010,
    acquisitionDetails: "Acquired by HP in 2019",
    lessonLearned:
      "Hardware-assisted isolation via micro-VMs was innovative but niche. Eventually integrated into HP's endpoint security suite.",
  },
  {
    id: slug("Mykonos Software", 2011),
    name: "Mykonos Software",
    year: 2011,
    winner: false,
    description: "Web application intrusion deception technology.",
    status: "acquired",
    category: "Application Security",
    acquisitionDetails: "Acquired by Juniper Networks in 2012 for $80M",
  },
  {
    id: slug("Zscaler", 2011),
    name: "Zscaler",
    year: 2011,
    winner: false,
    description:
      "Cloud-native secure web gateway and zero-trust network security.",
    status: "ipo",
    category: "Network Security",
    founded: 2007,
    ipoDetails: "IPO in 2018; market cap ~$25B+ as of 2025",
    lessonLearned:
      "Another non-winner that became a massive public company. Lesson: cloud-delivered security (SASE/SSE) was the right bet at the right time.",
  },
  {
    id: slug("Immun.io", 2011),
    name: "Immun.io",
    year: 2011,
    winner: false,
    description: "Runtime application self-protection (RASP).",
    status: "shutdown",
    category: "Application Security",
    shutdownDetails: "Company ceased operations; RASP market consolidated.",
  },
  {
    id: slug("Virtustream", 2011),
    name: "Virtustream",
    year: 2011,
    winner: false,
    description:
      "Cloud infrastructure management and migration for enterprise workloads.",
    status: "acquired",
    category: "Cloud Security",
    acquisitionDetails: "Acquired by EMC in 2015 for $1.2B; now part of Dell Technologies",
  },
  {
    id: slug("Cyphort", 2011),
    name: "Cyphort",
    year: 2011,
    winner: false,
    description: "Advanced threat detection using sandboxing and machine learning.",
    status: "acquired",
    category: "Threat Detection",
    acquisitionDetails: "Acquired by Juniper Networks in 2017",
  },
  {
    id: slug("PacketMotion", 2011),
    name: "PacketMotion",
    year: 2011,
    winner: false,
    description: "Network user activity monitoring and insider threat detection.",
    status: "acquired",
    category: "Network Security",
    acquisitionDetails: "Acquired by VMware in 2012",
  },
  {
    id: slug("Vaultive", 2011),
    name: "Vaultive",
    year: 2011,
    winner: false,
    description: "Cloud data encryption gateway for SaaS applications.",
    status: "shutdown",
    category: "Data Security",
    shutdownDetails: "Company shut down; cloud encryption gateways became features rather than products.",
    lessonLearned:
      "Cloud encryption proxy became a feature of CASB platforms, not a standalone product. Lesson: when your product is a feature, platform vendors will absorb you or kill you.",
  },
  {
    id: slug("Solera Networks", 2011),
    name: "Solera Networks",
    year: 2011,
    winner: false,
    description:
      "Full packet capture and network forensics platform.",
    status: "acquired",
    category: "Network Security",
    acquisitionDetails: "Acquired by Blue Coat Systems in 2013 for $105M; Blue Coat later acquired by Symantec",
  },

  // ===== 2012 =====
  {
    id: slug("Appthority", 2012),
    name: "Appthority",
    year: 2012,
    winner: true,
    description:
      "Mobile application risk management and app reputation scoring.",
    status: "acquired",
    category: "Endpoint Security",
    founded: 2011,
    acquisitionDetails: "Acquired by Symantec in 2018",
    notes: "Raised $6.3M post-win.",
    lessonLearned:
      "Mobile app risk scoring was ahead of its time. Lesson: being early in a market can work if you survive long enough for demand to catch up.",
  },
  {
    id: slug("CloudPassage", 2012),
    name: "CloudPassage",
    year: 2012,
    winner: false,
    description:
      "Automated security and compliance for cloud infrastructure (Halo platform).",
    status: "acquired",
    category: "Cloud Security",
    founded: 2010,
    acquisitionDetails: "Acquired by Fidelity National Information Services (FIS) in 2019",
  },
  {
    id: slug("Content Raven", 2012),
    name: "Content Raven",
    year: 2012,
    winner: false,
    description: "Secure content sharing and document DRM for enterprises.",
    status: "shutdown",
    category: "Data Security",
    shutdownDetails: "Company appears to have ceased operations.",
  },
  {
    id: slug("Dome9 Security", 2012),
    name: "Dome9 Security",
    year: 2012,
    winner: false,
    description: "Cloud security posture management (CSPM) for AWS and Azure.",
    status: "acquired",
    category: "Cloud Security",
    founded: 2011,
    acquisitionDetails: "Acquired by Check Point Software in 2018 for ~$175M",
    lessonLearned:
      "CSPM became a critical cloud security category. Lesson: early movers in cloud security config get acquired by firewall vendors seeking cloud relevance.",
  },
  {
    id: slug("Impermium", 2012),
    name: "Impermium",
    year: 2012,
    winner: false,
    description: "Social media and web platform abuse/fraud detection.",
    status: "acquired",
    category: "Threat Detection",
    acquisitionDetails: "Acquired by Google in 2014",
  },
  {
    id: slug("Sonatype", 2012),
    name: "Sonatype",
    year: 2012,
    winner: false,
    description:
      "Software supply chain security and open-source component management (Nexus).",
    status: "active",
    category: "Application Security",
    founded: 2008,
    notes: "Still active and growing; leader in software composition analysis (SCA).",
    lessonLearned:
      "Software supply chain security was prescient. Lesson: the SolarWinds and Log4j incidents proved this market's importance a decade later.",
  },
  {
    id: slug("Sumo Logic", 2012),
    name: "Sumo Logic",
    year: 2012,
    winner: false,
    description:
      "Cloud-native log management and security analytics (SIEM).",
    status: "acquired",
    category: "Security Operations",
    founded: 2010,
    ipoDetails: "IPO in 2020",
    acquisitionDetails: "Acquired by Francisco Partners in 2023 for $1.7B after going private",
    lessonLearned:
      "Cloud SIEM competed with Splunk. Lesson: going public then private shows the challenge of cloud SIEM economics against platform plays.",
  },

  // ===== 2013 =====
  {
    id: slug("Remotium", 2013),
    name: "Remotium",
    year: 2013,
    winner: true,
    description:
      "Secure mobile workspace delivering virtual applications to mobile devices.",
    status: "acquired",
    category: "Endpoint Security",
    founded: 2012,
    acquisitionDetails: "Acquired by Avast Software in 2015; all 15 employees joined Avast.",
    notes: "Raised $1M within 30 days of winning.",
    lessonLearned:
      "Mobile workspace virtualization was a valid approach but became a feature rather than a company. Lesson: acqui-hires can be a soft landing when the market picks simpler MDM/MAM approaches over elegant virtualization.",
  },
  {
    id: slug("Bluebox Security", 2013),
    name: "Bluebox Security",
    year: 2013,
    winner: false,
    description: "Mobile threat detection and app security testing.",
    status: "acquired",
    category: "Endpoint Security",
    acquisitionDetails: "Acquired by Lookout in 2015",
  },
  {
    id: slug("Cylera", 2013),
    name: "Cylera",
    year: 2013,
    winner: false,
    description: "IoT and medical device security analytics.",
    status: "active",
    category: "IoT / Hardware Security",
    notes: "Still active; healthcare IoT security is growing.",
  },
  {
    id: slug("Elastica", 2013),
    name: "Elastica",
    year: 2013,
    winner: false,
    description: "Cloud application security broker (CASB) with data science-driven threat detection.",
    status: "acquired",
    category: "Cloud Security",
    acquisitionDetails: "Acquired by Blue Coat Systems in 2015 for $280M; Blue Coat later acquired by Symantec",
    lessonLearned:
      "CASB was one of the hottest security categories of 2014-2016. Lesson: when Gartner creates a Magic Quadrant for your category, it's time to sell or scale fast.",
  },
  {
    id: slug("Light Point Security", 2013),
    name: "Light Point Security",
    year: 2013,
    winner: false,
    description: "Remote browser isolation (RBI) platform.",
    status: "acquired",
    category: "Network Security",
    acquisitionDetails: "Acquired by McAfee in 2018",
  },
  {
    id: slug("Mashape", 2013),
    name: "Mashape",
    year: 2013,
    winner: false,
    description: "API marketplace and API management (later became Kong).",
    status: "active",
    category: "Application Security",
    notes: "Rebranded as Kong Inc.; became a leading API gateway provider.",
    lessonLearned:
      "API management pivoted from marketplace to gateway/mesh. Lesson: the pivot from marketplace to infrastructure platform unlocked the real value.",
  },
  {
    id: slug("Morta Security", 2013),
    name: "Morta Security",
    year: 2013,
    winner: false,
    description: "Advanced threat protection and breach detection.",
    status: "acquired",
    category: "Threat Detection",
    acquisitionDetails: "Acquired by Palo Alto Networks in 2014",
  },
  {
    id: slug("Perspecsys", 2013),
    name: "Perspecsys",
    year: 2013,
    winner: false,
    description: "Cloud data protection and tokenization gateway.",
    status: "acquired",
    category: "Data Security",
    acquisitionDetails: "Acquired by Blue Coat Systems in 2015; Blue Coat later acquired by Symantec",
  },
  {
    id: slug("ThreatStream", 2013),
    name: "ThreatStream",
    year: 2013,
    winner: false,
    description: "Threat intelligence platform aggregating and operationalizing threat data.",
    status: "acquired",
    category: "Threat Detection",
    acquisitionDetails: "Rebranded as Anomali; raised significant funding; still active as Anomali",
    notes: "Rebranded to Anomali in 2016.",
  },
  {
    id: slug("Vormetric", 2013),
    name: "Vormetric",
    year: 2013,
    winner: false,
    description: "Data-at-rest encryption and key management.",
    status: "acquired",
    category: "Data Security",
    acquisitionDetails: "Acquired by Thales in 2016 for $400M",
  },

  // ===== 2014 =====
  {
    id: slug("RedOwl", 2014),
    name: "RedOwl",
    year: 2014,
    winner: true,
    description:
      "Insider threat detection using behavior analytics on employee communications and activity.",
    status: "acquired",
    category: "Threat Detection",
    founded: 2011,
    acquisitionDetails: "Acquired by Forcepoint in 2017",
    lessonLearned:
      "Insider threat analytics was compelling but privacy concerns slowed adoption. Lesson: employee monitoring solutions face cultural headwinds regardless of technical merit.",
  },
  {
    id: slug("Cylance", 2014),
    name: "Cylance",
    year: 2014,
    winner: false,
    description:
      "AI/ML-based endpoint protection that prevents malware pre-execution using mathematical models.",
    status: "acquired",
    category: "Endpoint Security",
    founded: 2012,
    acquisitionDetails: "Acquired by BlackBerry in 2019 for $1.4B",
    notes: "Raised $300M in funding; most commercially successful 2014 finalist.",
    lessonLearned:
      "ML-first endpoint protection was revolutionary but got absorbed into a declining platform (BlackBerry). Lesson: who acquires you matters as much as the acquisition price.",
  },
  {
    id: slug("Aorato", 2014),
    name: "Aorato",
    year: 2014,
    winner: false,
    description: "Active Directory security and identity attack detection.",
    status: "acquired",
    category: "Identity & Access",
    acquisitionDetails: "Acquired by Microsoft in 2014 for ~$200M; became Microsoft Advanced Threat Analytics (ATA) / Defender for Identity",
    lessonLearned:
      "AD security became a critical Microsoft product. Lesson: if your product protects a Microsoft asset, Microsoft will buy you.",
  },
  {
    id: slug("Vectra AI", 2014),
    name: "Vectra AI",
    year: 2014,
    winner: false,
    description:
      "AI-driven network detection and response (NDR) for real-time cyberattack identification.",
    status: "active",
    category: "Threat Detection",
    founded: 2012,
    notes: "Valued at $1.2B+ as of 2022; still independent and growing.",
    lessonLearned:
      "NDR category pioneer. Lesson: patience and category leadership can sustain an independent security company.",
  },
  {
    id: slug("TrustInSoft", 2014),
    name: "TrustInSoft",
    year: 2014,
    winner: false,
    description: "Formal methods and mathematical verification for C/C++ code security.",
    status: "active",
    category: "Application Security",
    founded: 2013,
  },
  {
    id: slug("Fortscale", 2014),
    name: "Fortscale",
    year: 2014,
    winner: false,
    description: "User and entity behavior analytics (UEBA) for insider threat detection.",
    status: "acquired",
    category: "Threat Detection",
    acquisitionDetails: "Merged with Presidio Identity to form Fortscale; eventually wound down or absorbed",
  },
  {
    id: slug("Lightspin", 2014),
    name: "Vera",
    year: 2014,
    winner: false,
    description: "Digital rights management (DRM) and file-level encryption for enterprise documents.",
    status: "acquired",
    category: "Data Security",
    acquisitionDetails: "Acquired by HelpSystems (now Fortra) in 2020",
  },
  {
    id: slug("TaaSera", 2014),
    name: "TaaSera",
    year: 2014,
    winner: false,
    description: "Threat detection through network behavior analysis of pre-breach activity.",
    status: "shutdown",
    category: "Threat Detection",
    shutdownDetails: "Company appears to have shut down.",
  },
  {
    id: slug("Trusted Objects", 2014),
    name: "Trusted Objects",
    year: 2014,
    winner: false,
    description: "Security for IoT devices and embedded systems using secure elements.",
    status: "active",
    category: "IoT / Hardware Security",
    founded: 2013,
  },
  {
    id: slug("Bitglass", 2014),
    name: "Bitglass",
    year: 2014,
    winner: false,
    description: "Cloud access security broker (CASB) and cloud DLP.",
    status: "acquired",
    category: "Cloud Security",
    founded: 2013,
    acquisitionDetails: "Acquired by Forcepoint in 2021",
  },

  // ===== 2015 =====
  {
    id: slug("Waratek", 2015),
    name: "Waratek",
    year: 2015,
    winner: true,
    description:
      "Runtime application self-protection (RASP) and virtual patching for Java applications.",
    status: "active",
    category: "Application Security",
    founded: 2009,
    lessonLearned:
      "RASP and virtual patching for Java — practical but niche. Lesson: winning the Sandbox with a solid product doesn't mean the market will be huge.",
  },
  {
    id: slug("SentinelOne", 2015),
    name: "SentinelOne",
    year: 2015,
    winner: false,
    description:
      "Autonomous AI-powered endpoint detection and response (EDR) platform.",
    status: "ipo",
    category: "Endpoint Security",
    founded: 2013,
    ipoDetails: "IPO in 2021 at $10.9B valuation; peaked over $18B market cap",
    lessonLearned:
      "Didn't win the Sandbox but became a top-5 cybersecurity company by market cap. Lesson: autonomous EDR was the right product at the right time, and execution beat contest wins.",
  },
  {
    id: slug("CyberReason", 2015),
    name: "Cybereason",
    year: 2015,
    winner: false,
    description:
      "Endpoint detection and response using behavioral analysis and operation-centric approach.",
    status: "active",
    category: "Endpoint Security",
    founded: 2012,
    notes: "Reached $3.2B valuation but has struggled recently.",
    lessonLearned:
      "Massive valuation but couldn't IPO. Lesson: in the EDR wars, only the top 2-3 vendors survive as independents; the rest consolidate.",
  },
  {
    id: slug("Phantom", 2015),
    name: "Phantom",
    year: 2015,
    winner: false,
    description:
      "Security orchestration, automation, and response (SOAR) platform.",
    status: "acquired",
    category: "Security Operations",
    founded: 2014,
    acquisitionDetails: "Acquired by Splunk in 2018 for $350M; Splunk later acquired by Cisco for $28B",
    notes: "Also appeared as 2016 winner.",
    lessonLearned:
      "SOAR pioneer. Lesson: automation in security ops was the right bet; getting acquired by Splunk (then Cisco) validated the approach.",
  },
  {
    id: slug("SecurityDo", 2015),
    name: "SecurityDo (Fluency)",
    year: 2015,
    winner: false,
    description: "Security analytics and log management platform.",
    status: "active",
    category: "Security Operations",
    notes: "Rebranded as Fluency Security.",
  },
  {
    id: slug("Bastille Networks", 2015),
    name: "Bastille Networks",
    year: 2015,
    winner: false,
    description: "RF (radio frequency) threat detection for enterprise IoT and wireless security.",
    status: "active",
    category: "IoT / Hardware Security",
    founded: 2014,
  },
  {
    id: slug("Prevoty", 2015),
    name: "Prevoty",
    year: 2015,
    winner: false,
    description: "Runtime application security and autonomous protection.",
    status: "acquired",
    category: "Application Security",
    acquisitionDetails: "Acquired by Imperva in 2018",
  },
  {
    id: slug("Menlo Security", 2015),
    name: "Menlo Security",
    year: 2015,
    winner: false,
    description: "Isolation-based web security platform eliminating malware from web/email.",
    status: "active",
    category: "Network Security",
    founded: 2013,
    notes: "Raised $260M+; still active and growing.",
  },
  {
    id: slug("ProtectWise", 2015),
    name: "ProtectWise",
    year: 2015,
    winner: false,
    description: "Cloud-based network detection and response with full packet capture visualization.",
    status: "acquired",
    category: "Network Security",
    acquisitionDetails: "Acquired by Verizon in 2019",
  },
  {
    id: slug("Dtex Systems", 2015),
    name: "Dtex Systems",
    year: 2015,
    winner: false,
    description: "Insider threat detection and user behavior intelligence.",
    status: "acquired",
    category: "Threat Detection",
    acquisitionDetails: "Merged with CISO Global; later acquired by Proofpoint in 2023",
  },

  // ===== 2016 =====
  {
    id: slug("Phantom Cyber", 2016),
    name: "Phantom Cyber",
    year: 2016,
    winner: true,
    description:
      "Security orchestration, automation and response (SOAR) — automate playbooks across security tools.",
    status: "acquired",
    category: "Security Operations",
    founded: 2014,
    acquisitionDetails: "Acquired by Splunk in 2018 for $350M; Splunk acquired by Cisco in 2024 for $28B",
    lessonLearned:
      "Defined the SOAR category. Lesson: building a platform that integrates with other tools (rather than replacing them) is a powerful go-to-market wedge.",
  },
  {
    id: slug("Bastille Networks-2016", 2016),
    name: "Bastille Networks",
    year: 2016,
    winner: false,
    description: "Enterprise RF threat detection for IoT/wireless security.",
    status: "active",
    category: "IoT / Hardware Security",
    founded: 2014,
  },
  {
    id: slug("Illusive Networks", 2016),
    name: "Illusive Networks",
    year: 2016,
    winner: false,
    description: "Deception-based cybersecurity — creates fake credentials and data trails to detect attackers.",
    status: "acquired",
    category: "Threat Detection",
    acquisitionDetails: "Acquired by Proofpoint in 2022",
  },
  {
    id: slug("Menlo Security-2016", 2016),
    name: "Menlo Security",
    year: 2016,
    winner: false,
    description: "Cloud-based isolation platform for web and email security.",
    status: "active",
    category: "Network Security",
    founded: 2013,
  },
  {
    id: slug("Prevoty-2016", 2016),
    name: "Prevoty",
    year: 2016,
    winner: false,
    description: "Runtime application self-protection (RASP).",
    status: "acquired",
    category: "Application Security",
    acquisitionDetails: "Acquired by Imperva in 2018",
  },
  {
    id: slug("ProtectWise-2016", 2016),
    name: "ProtectWise",
    year: 2016,
    winner: false,
    description: "Cloud-delivered NDR with immersive 3D visualization of network threats.",
    status: "acquired",
    category: "Network Security",
    acquisitionDetails: "Acquired by Verizon in 2019",
  },
  {
    id: slug("SafeBreach", 2016),
    name: "SafeBreach",
    year: 2016,
    winner: false,
    description: "Breach and attack simulation (BAS) platform for continuous security validation.",
    status: "active",
    category: "Vulnerability Management",
    founded: 2014,
    notes: "Still active; BAS has become a recognized market category.",
  },
  {
    id: slug("Skyport Systems", 2016),
    name: "Skyport Systems",
    year: 2016,
    winner: false,
    description: "Trusted computing infrastructure with hardware-rooted security.",
    status: "acquired",
    category: "Cloud Security",
    acquisitionDetails: "Acquired by Cisco in 2018",
  },
  {
    id: slug("Vera-2016", 2016),
    name: "Vera",
    year: 2016,
    winner: false,
    description: "File-level security and DRM for enterprise content.",
    status: "acquired",
    category: "Data Security",
    acquisitionDetails: "Acquired by HelpSystems (Fortra) in 2020",
  },
  {
    id: slug("Versa Networks", 2016),
    name: "Versa Networks",
    year: 2016,
    winner: false,
    description: "SD-WAN and SASE platform combining networking and security.",
    status: "active",
    category: "Network Security",
    founded: 2012,
    notes: "Raised $300M+; major SD-WAN/SASE player.",
  },

  // ===== 2017 =====
  {
    id: slug("UnifyID", 2017),
    name: "UnifyID",
    year: 2017,
    winner: true,
    description:
      "Implicit authentication using machine learning on sensor data (gait, environment) for passwordless identity.",
    status: "shutdown",
    category: "Identity & Access",
    founded: 2015,
    shutdownDetails: "Company ceased operations around 2022. Behavioral biometrics for passive authentication didn't achieve product-market fit.",
    lessonLearned:
      "Passive biometric authentication was too early and too abstract for enterprises. Lesson: winning the Sandbox with cool demo tech doesn't mean enterprise buyers will adopt it.",
  },
  {
    id: slug("Obsidian Security", 2017),
    name: "Obsidian Security",
    year: 2017,
    winner: false,
    description: "Cloud detection and response for SaaS application security.",
    status: "active",
    category: "Cloud Security",
    founded: 2017,
    notes: "Raised significant funding; active in SSPM/CDR space.",
  },
  {
    id: slug("EnVeil", 2017),
    name: "EnVeil",
    year: 2017,
    winner: false,
    description: "Homomorphic encryption and encrypted search — compute on encrypted data without decryption.",
    status: "acquired",
    category: "Data Security",
    acquisitionDetails: "Acquired by Ellison Technologies",
    notes: "1st runner-up in 2017.",
    lessonLearned:
      "Homomorphic encryption remains promising but performance overhead limits real-world use. Lesson: cryptographic breakthroughs need practical performance to reach adoption.",
  },
  {
    id: slug("Claroty", 2017),
    name: "Claroty",
    year: 2017,
    winner: false,
    description: "OT/IoT/ICS security platform for industrial control systems and critical infrastructure.",
    status: "active",
    category: "IoT / Hardware Security",
    founded: 2015,
    notes: "Raised $600M+; valued at $1.5B+; leader in OT security.",
    lessonLearned:
      "OT security became critical infrastructure priority. Lesson: timing with ICS/OT threat landscape expansion was perfect.",
  },
  {
    id: slug("Mashero", 2017),
    name: "Mashero",
    year: 2017,
    winner: false,
    description: "API security and protection against bot attacks.",
    status: "shutdown",
    category: "Application Security",
    shutdownDetails: "Company no longer appears operational.",
  },
  {
    id: slug("Awake Security", 2017),
    name: "Awake Security",
    year: 2017,
    winner: false,
    description: "Network detection and response (NDR) using AI-driven entity analysis.",
    status: "acquired",
    category: "Network Security",
    acquisitionDetails: "Acquired by Arista Networks in 2020",
  },
  {
    id: slug("ShieldX Networks", 2017),
    name: "ShieldX Networks",
    year: 2017,
    winner: false,
    description: "Multi-cloud micro-segmentation and network security.",
    status: "shutdown",
    category: "Cloud Security",
    shutdownDetails: "Company ceased operations around 2021.",
    lessonLearned:
      "Multi-cloud micro-segmentation was crowded. Lesson: when multiple well-funded competitors solve the same problem, capital alone can't save you.",
  },
  {
    id: slug("Solebit", 2017),
    name: "Solebit",
    year: 2017,
    winner: false,
    description: "Deep inspection for detecting evasive malware and document-based threats.",
    status: "acquired",
    category: "Threat Detection",
    acquisitionDetails: "Acquired by Mimecast in 2018",
  },
  {
    id: slug("GreatHorn", 2017),
    name: "GreatHorn",
    year: 2017,
    winner: false,
    description: "Cloud-native email security using behavioral AI.",
    status: "acquired",
    category: "Threat Detection",
    acquisitionDetails: "Acquired by Barracuda Networks in 2022",
  },
  {
    id: slug("Dispel", 2017),
    name: "Dispel",
    year: 2017,
    winner: false,
    description: "Secure remote access using disposable virtual infrastructure.",
    status: "active",
    category: "Network Security",
    founded: 2015,
  },

  // ===== 2018 =====
  {
    id: slug("BigID", 2018),
    name: "BigID",
    year: 2018,
    winner: true,
    description:
      "Data intelligence platform for privacy, protection, and governance — discover and classify personal data at scale.",
    status: "active",
    category: "Privacy & Compliance",
    founded: 2016,
    notes: "Valued at $1.25B (unicorn). One of the most successful ISB winners.",
    lessonLearned:
      "GDPR timing was perfect. Lesson: regulatory tailwinds (GDPR, CCPA) can create billion-dollar companies overnight if you're in the right category.",
  },
  {
    id: slug("Acalvio", 2018),
    name: "Acalvio Technologies",
    year: 2018,
    winner: false,
    description: "Autonomous deception technology using AI-driven honeypots and decoys.",
    status: "active",
    category: "Threat Detection",
    founded: 2015,
  },
  {
    id: slug("BluVector", 2018),
    name: "BluVector",
    year: 2018,
    winner: false,
    description: "AI-powered network detection for fileless malware and advanced threats.",
    status: "acquired",
    category: "Threat Detection",
    acquisitionDetails: "Acquired by Comcast in 2019",
  },
  {
    id: slug("CyberGRX", 2018),
    name: "CyberGRX",
    year: 2018,
    winner: false,
    description: "Third-party cyber risk management exchange and assessment platform.",
    status: "acquired",
    category: "Security Operations",
    acquisitionDetails: "Merged with ProcessUnity in 2023",
  },
  {
    id: slug("Fortanix", 2018),
    name: "Fortanix",
    year: 2018,
    winner: false,
    description: "Runtime encryption and confidential computing using Intel SGX enclaves.",
    status: "active",
    category: "Data Security",
    founded: 2016,
    notes: "Raised $90M+; leader in confidential computing.",
  },
  {
    id: slug("Hysolate", 2018),
    name: "Hysolate",
    year: 2018,
    winner: false,
    description: "Endpoint isolation using OS-level virtual workspaces.",
    status: "shutdown",
    category: "Endpoint Security",
    shutdownDetails: "Company appears to have pivoted and then ceased operations.",
  },
  {
    id: slug("ReFirm Labs", 2018),
    name: "ReFirm Labs",
    year: 2018,
    winner: false,
    description: "IoT firmware security analysis and binary scanning.",
    status: "acquired",
    category: "IoT / Hardware Security",
    acquisitionDetails: "Acquired by Microsoft in 2021",
    lessonLearned:
      "Firmware security became critical for IoT. Lesson: Microsoft's IoT ambitions made firmware scanning strategically valuable.",
  },
  {
    id: slug("ShiftLeft", 2018),
    name: "ShiftLeft",
    year: 2018,
    winner: false,
    description: "Application security testing (SAST/DAST) with code property graphs.",
    status: "acquired",
    category: "Application Security",
    acquisitionDetails: "Merged with Qwiet AI in 2023",
  },
  {
    id: slug("Awake Security-2018", 2018),
    name: "Awake Security",
    year: 2018,
    winner: false,
    description: "Network traffic analysis using entity-based security model.",
    status: "acquired",
    category: "Network Security",
    acquisitionDetails: "Acquired by Arista Networks in 2020",
  },
  {
    id: slug("Securiti", 2018),
    name: "Securiti.ai",
    year: 2018,
    winner: false,
    description: "AI-driven data privacy and governance automation.",
    status: "acquired",
    category: "Privacy & Compliance",
    notes: "Also appeared as 2020 winner.",
    acquisitionDetails: "Acquired by Veeam in 2025 for $1.725B",
  },

  // ===== 2019 =====
  {
    id: slug("Axonius", 2019),
    name: "Axonius",
    year: 2019,
    winner: true,
    description:
      "Cybersecurity asset management platform — aggregates data from all security tools to give unified visibility.",
    status: "active",
    category: "Security Operations",
    founded: 2017,
    notes: "Valued at $2.6B; often cited as one of the most successful ISB winners.",
    lessonLearned:
      "Asset visibility sounds boring but it's foundational. Lesson: the unsexy 'Toyota Camry of cybersecurity' can be worth billions if every CISO needs it.",
  },
  {
    id: slug("Arkose Labs", 2019),
    name: "Arkose Labs",
    year: 2019,
    winner: false,
    description: "Fraud and bot detection using adaptive challenges.",
    status: "active",
    category: "Threat Detection",
    founded: 2015,
  },
  {
    id: slug("Cloudknox", 2019),
    name: "CloudKnox Security",
    year: 2019,
    winner: false,
    description: "Cloud infrastructure entitlement management (CIEM) — manage and reduce cloud permissions.",
    status: "acquired",
    category: "Cloud Security",
    acquisitionDetails: "Acquired by Microsoft in 2021; became Microsoft Entra Permissions Management",
    lessonLearned:
      "CIEM became a critical cloud security capability. Lesson: identity-centric cloud security is a must-have, and Microsoft buys what it can't build fast enough.",
  },
  {
    id: slug("Dflabs", 2019),
    name: "DFLabs",
    year: 2019,
    winner: false,
    description: "Security orchestration, automation and response (SOAR) with case management.",
    status: "acquired",
    category: "Security Operations",
    acquisitionDetails: "Acquired by Sumo Logic in 2021",
  },
  {
    id: slug("DisruptOps", 2019),
    name: "DisruptOps",
    year: 2019,
    winner: false,
    description: "Cloud security operations automation.",
    status: "acquired",
    category: "Cloud Security",
    acquisitionDetails: "Acquired by FireMon in 2021",
  },
  {
    id: slug("Eclypsium", 2019),
    name: "Eclypsium",
    year: 2019,
    winner: false,
    description: "Firmware and hardware-level security for enterprise devices and supply chains.",
    status: "active",
    category: "IoT / Hardware Security",
    founded: 2017,
  },
  {
    id: slug("Salt Security", 2019),
    name: "Salt Security",
    year: 2019,
    winner: false,
    description: "API security platform using AI/ML for threat detection in API traffic.",
    status: "active",
    category: "Application Security",
    founded: 2016,
    notes: "Raised $270M+; valued at $1.4B.",
  },
  {
    id: slug("Capsule8", 2019),
    name: "Capsule8",
    year: 2019,
    winner: false,
    description: "Real-time detection and response for Linux production environments.",
    status: "acquired",
    category: "Cloud Security",
    acquisitionDetails: "Acquired by Sophos in 2021",
  },
  {
    id: slug("WireWheel", 2019),
    name: "WireWheel",
    year: 2019,
    winner: false,
    description: "Privacy management and data rights automation platform.",
    status: "acquired",
    category: "Privacy & Compliance",
    acquisitionDetails: "Acquired by Mimecast in 2022",
  },
  {
    id: slug("Thoropass", 2019),
    name: "Duality Technologies",
    year: 2019,
    winner: false,
    description: "Privacy-enhancing computation using homomorphic encryption.",
    status: "acquired",
    category: "Data Security",
    acquisitionDetails: "Acquired by Baffle in 2023",
  },

  // ===== 2020 =====
  {
    id: slug("Securiti.ai", 2020),
    name: "Securiti.ai",
    year: 2020,
    winner: true,
    description:
      "PrivacyOps platform combining AI-powered data discovery, DSR automation, and compliance management.",
    status: "acquired",
    category: "Privacy & Compliance",
    founded: 2018,
    acquisitionDetails: "Acquired by Veeam in December 2025 for $1.725B",
    lessonLearned:
      "Privacy automation at the right regulatory moment. Lesson: GDPR/CCPA created a rush for automated compliance, and the winner captured massive value.",
  },
  {
    id: slug("AppOmni", 2020),
    name: "AppOmni",
    year: 2020,
    winner: false,
    description: "SaaS security posture management (SSPM) for enterprise SaaS environments.",
    status: "active",
    category: "Cloud Security",
    founded: 2018,
    notes: "Raised $100M+.",
  },
  {
    id: slug("BluBracket", 2020),
    name: "BluBracket",
    year: 2020,
    winner: false,
    description: "Code security for detecting secrets and PII in source code repositories.",
    status: "acquired",
    category: "Application Security",
    acquisitionDetails: "Acquired by Palo Alto Networks in 2023",
  },
  {
    id: slug("Elevate Security", 2020),
    name: "Elevate Security",
    year: 2020,
    winner: false,
    description: "Human risk quantification and employee security behavior scoring.",
    status: "active",
    category: "Security Operations",
  },
  {
    id: slug("Sqreen", 2020),
    name: "Sqreen",
    year: 2020,
    winner: false,
    description: "In-app security monitoring and protection (RASP + WAF).",
    status: "acquired",
    category: "Application Security",
    acquisitionDetails: "Acquired by Datadog in 2021",
    lessonLearned:
      "RASP embedded in observability. Lesson: security that lives inside the observability pipeline is where the market is heading.",
  },
  {
    id: slug("Tala Security", 2020),
    name: "Tala Security",
    year: 2020,
    winner: false,
    description: "Client-side web security protecting against Magecart-style attacks.",
    status: "acquired",
    category: "Application Security",
    acquisitionDetails: "Acquired by Cloudflare in 2021",
  },
  {
    id: slug("Vulcan Cyber", 2020),
    name: "Vulcan Cyber",
    year: 2020,
    winner: false,
    description: "Vulnerability remediation orchestration — prioritize and fix vulns across tools.",
    status: "active",
    category: "Vulnerability Management",
    founded: 2018,
  },
  {
    id: slug("SECURITI", 2020),
    name: "Pixm",
    year: 2020,
    winner: false,
    description: "Computer vision-based anti-phishing for detecting fake login pages.",
    status: "active",
    category: "Threat Detection",
    founded: 2018,
  },
  {
    id: slug("Inky", 2020),
    name: "Inky",
    year: 2020,
    winner: false,
    description: "AI-powered email security using computer vision and machine learning.",
    status: "active",
    category: "Threat Detection",
    founded: 2015,
  },
  {
    id: slug("Obsidian Security-2020", 2020),
    name: "Obsidian Security",
    year: 2020,
    winner: false,
    description: "SaaS security and cloud detection/response.",
    status: "active",
    category: "Cloud Security",
    founded: 2017,
  },

  // ===== 2021 =====
  {
    id: slug("Apiiro", 2021),
    name: "Apiiro",
    year: 2021,
    winner: true,
    description:
      "Code risk platform that analyzes code changes in real-time to identify risks before they reach production.",
    status: "active",
    category: "Application Security",
    founded: 2019,
    notes: "Raised $100M+.",
    lessonLearned:
      "Shift-left risk analysis connecting code to cloud. Lesson: developers making security decisions need context, not just alerts.",
  },
  {
    id: slug("Wiz", 2021),
    name: "Wiz",
    year: 2021,
    winner: false,
    description:
      "Agentless cloud security platform scanning entire cloud environments for risks across VMs, containers, and serverless.",
    status: "acquired",
    category: "Cloud Security",
    founded: 2020,
    acquisitionDetails: "Acquired by Google/Alphabet in 2025 for ~$32B",
    lessonLearned:
      "Didn't win the Sandbox but became the biggest cybersecurity acquisition in history. Lesson: fastest-growing security startup ever proved that agentless cloud scanning + amazing UX beats everything.",
  },
  {
    id: slug("Abnormal Security", 2021),
    name: "Abnormal Security",
    year: 2021,
    winner: false,
    description: "AI-based email security using behavioral analysis to detect business email compromise (BEC).",
    status: "active",
    category: "Threat Detection",
    founded: 2018,
    notes: "Valued at $4B+.",
  },
  {
    id: slug("Axis Security", 2021),
    name: "Axis Security",
    year: 2021,
    winner: false,
    description: "Zero-trust network access (ZTNA) as a service.",
    status: "acquired",
    category: "Network Security",
    acquisitionDetails: "Acquired by Hewlett Packard Enterprise (HPE) in 2023",
  },
  {
    id: slug("Cape Privacy", 2021),
    name: "Cape Privacy",
    year: 2021,
    winner: false,
    description: "Encrypted data collaboration using secure multi-party computation.",
    status: "shutdown",
    category: "Data Security",
    shutdownDetails: "Company pivoted to Cape (AI anonymization) then shut down secure computation product.",
  },
  {
    id: slug("Deduce", 2021),
    name: "Deduce",
    year: 2021,
    winner: false,
    description: "Identity fraud prevention using a network of anonymized identity signals.",
    status: "active",
    category: "Identity & Access",
  },
  {
    id: slug("Open Raven", 2021),
    name: "Open Raven",
    year: 2021,
    winner: false,
    description: "Cloud-native data discovery and classification for data security posture management.",
    status: "active",
    category: "Data Security",
    founded: 2019,
  },
  {
    id: slug("Satori Cyber", 2021),
    name: "Satori",
    year: 2021,
    winner: false,
    description: "DataSecOps platform — universal data access control and security for databases and data lakes.",
    status: "acquired",
    category: "Data Security",
    acquisitionDetails: "Acquired by Hive (part of Cisco/ThousandEyes)",
  },
  {
    id: slug("Strata Identity", 2021),
    name: "Strata Identity",
    year: 2021,
    winner: false,
    description: "Identity orchestration for multi-cloud and hybrid environments.",
    status: "active",
    category: "Identity & Access",
    founded: 2019,
  },
  {
    id: slug("WABBI", 2021),
    name: "WABBI",
    year: 2021,
    winner: false,
    description: "Continuous security and compliance governance for DevSecOps pipelines.",
    status: "active",
    category: "Application Security",
  },

  // ===== 2022 =====
  {
    id: slug("Talon Cyber Security", 2022),
    name: "Talon Cyber Security",
    year: 2022,
    winner: true,
    description:
      "Enterprise browser — secure, managed browser for distributed workforces replacing VDI.",
    status: "acquired",
    category: "Endpoint Security",
    founded: 2021,
    acquisitionDetails: "Acquired by Palo Alto Networks in December 2023 for ~$625M",
    lessonLearned:
      "Enterprise browser became a hot new category. Lesson: the browser as the new endpoint struck a nerve, and getting acquired by Palo Alto within 2 years shows how fast things move in cyber.",
  },
  {
    id: slug("Torq", 2022),
    name: "Torq",
    year: 2022,
    winner: false,
    description: "No-code security automation and orchestration platform.",
    status: "active",
    category: "Security Operations",
    founded: 2020,
    notes: "Raised $150M+.",
  },
  {
    id: slug("Dasera", 2022),
    name: "Dasera",
    year: 2022,
    winner: false,
    description: "Automated data governance and security for cloud data stores.",
    status: "active",
    category: "Data Security",
    founded: 2019,
  },
  {
    id: slug("Lightspin-2022", 2022),
    name: "Lightspin",
    year: 2022,
    winner: false,
    description: "Cloud security posture management with attack path analysis.",
    status: "acquired",
    category: "Cloud Security",
    acquisitionDetails: "Acquired by Cisco in 2023",
  },
  {
    id: slug("Neosec", 2022),
    name: "Neosec",
    year: 2022,
    winner: false,
    description: "API security using XDR-like behavioral analytics for API traffic.",
    status: "acquired",
    category: "Application Security",
    acquisitionDetails: "Acquired by Akamai in 2023",
  },
  {
    id: slug("Sevco Security", 2022),
    name: "Sevco Security",
    year: 2022,
    winner: false,
    description: "Cloud-native asset intelligence to find and fix gaps in security tool coverage.",
    status: "active",
    category: "Security Operations",
    founded: 2020,
  },
  {
    id: slug("Spin.AI", 2022),
    name: "Spin.AI",
    year: 2022,
    winner: false,
    description: "SaaS security for protecting data in SaaS applications (Google Workspace, Microsoft 365).",
    status: "active",
    category: "Cloud Security",
  },
  {
    id: slug("BastionZero", 2022),
    name: "BastionZero",
    year: 2022,
    winner: false,
    description: "Zero-trust infrastructure access for remote access to servers, containers, and clusters.",
    status: "acquired",
    category: "Identity & Access",
    acquisitionDetails: "Acquired by Cloudflare in 2024",
  },
  {
    id: slug("Cado Security", 2022),
    name: "Cado Security",
    year: 2022,
    winner: false,
    description: "Cloud-native digital forensics and incident response (DFIR).",
    status: "acquired",
    category: "Security Operations",
    acquisitionDetails: "Acquired by Darktrace in 2024",
  },
  {
    id: slug("Cycode", 2022),
    name: "Cycode",
    year: 2022,
    winner: false,
    description: "Software supply chain security — protect CI/CD pipelines and source code.",
    status: "active",
    category: "Application Security",
    founded: 2019,
  },

  // ===== 2023 =====
  {
    id: slug("HiddenLayer", 2023),
    name: "HiddenLayer",
    year: 2023,
    winner: true,
    description:
      "AI/ML model security platform — protect machine learning models from adversarial attacks, model theft, and inference manipulation.",
    status: "active",
    category: "AI Security",
    founded: 2022,
    lessonLearned:
      "First AI-security-focused winner, perfectly timed with GenAI explosion. Lesson: protecting AI models (not just using AI for security) is a new frontier.",
  },
  {
    id: slug("Pangea", 2023),
    name: "Pangea",
    year: 2023,
    winner: false,
    description: "Security-as-code APIs — embeddable security services (auth, vault, audit) for developers.",
    status: "active",
    category: "Application Security",
    founded: 2021,
  },
  {
    id: slug("Dazz", 2023),
    name: "Dazz",
    year: 2023,
    winner: false,
    description: "Cloud security remediation platform unifying findings across tools.",
    status: "acquired",
    category: "Cloud Security",
    acquisitionDetails: "Acquired by Wiz in November 2024 for ~$450M",
    lessonLearned:
      "Remediation (not just detection) became the differentiator. Lesson: ISB finalists acquiring other ISB finalists (Wiz buying Dazz) shows the ecosystem's compounding effect.",
  },
  {
    id: slug("Endor Labs", 2023),
    name: "Endor Labs",
    year: 2023,
    winner: false,
    description: "Dependency lifecycle management — secure open-source selection and vulnerability management.",
    status: "active",
    category: "Application Security",
    founded: 2021,
    notes: "Raised $70M+.",
  },
  {
    id: slug("Zama", 2023),
    name: "Zama",
    year: 2023,
    winner: false,
    description: "Open-source fully homomorphic encryption (FHE) tools for developers.",
    status: "active",
    category: "Data Security",
    founded: 2020,
  },
  {
    id: slug("Relyance AI", 2023),
    name: "Relyance AI",
    year: 2023,
    winner: false,
    description: "Data governance using AI to trace data flows and enforce privacy policies in code.",
    status: "active",
    category: "Privacy & Compliance",
    founded: 2020,
  },
  {
    id: slug("SafeBase", 2023),
    name: "SafeBase",
    year: 2023,
    winner: false,
    description: "Smart trust center for automating security questionnaires and compliance sharing.",
    status: "active",
    category: "Privacy & Compliance",
    founded: 2020,
  },
  {
    id: slug("Valence Security", 2023),
    name: "Valence Security",
    year: 2023,
    winner: false,
    description: "SaaS security posture management with focus on SaaS-to-SaaS supply chain risks.",
    status: "active",
    category: "Cloud Security",
    founded: 2021,
  },
  {
    id: slug("Astrix Security", 2023),
    name: "Astrix Security",
    year: 2023,
    winner: false,
    description: "Non-human identity security — secure service accounts, API keys, and machine identities.",
    status: "active",
    category: "Identity & Access",
    founded: 2021,
    lessonLearned:
      "Non-human identity security emerged as a category. Lesson: as APIs and service accounts proliferate, managing non-human identities becomes critical.",
  },
  {
    id: slug("AnChain.AI", 2023),
    name: "AnChain.AI",
    year: 2023,
    winner: false,
    description: "Blockchain security and crypto compliance using AI-powered analytics.",
    status: "active",
    category: "Other",
    founded: 2018,
  },

  // ===== 2024 =====
  {
    id: slug("Reality Defender", 2024),
    name: "Reality Defender",
    year: 2024,
    winner: true,
    description:
      "Deepfake and AI-generated media detection platform for enterprises and governments.",
    status: "active",
    category: "AI Security",
    founded: 2021,
    lessonLearned:
      "Deepfake detection became critical as generative AI exploded. Lesson: the flip side of GenAI innovation is GenAI-powered fraud, creating an entirely new security category.",
  },
  {
    id: slug("Harmonic Security", 2024),
    name: "Harmonic Security",
    year: 2024,
    winner: false,
    description: "Data protection for GenAI — prevent sensitive data from leaking into LLMs and AI tools.",
    status: "active",
    category: "AI Security",
    founded: 2023,
  },
  {
    id: slug("Dropzone AI", 2024),
    name: "Dropzone AI",
    year: 2024,
    winner: false,
    description: "AI-powered SOC analyst that autonomously investigates security alerts.",
    status: "active",
    category: "Security Operations",
    founded: 2023,
  },
  {
    id: slug("Bedrock Security", 2024),
    name: "Bedrock Security",
    year: 2024,
    winner: false,
    description: "Data security posture management (DSPM) for protecting sensitive data across clouds.",
    status: "active",
    category: "Data Security",
    founded: 2022,
  },
  {
    id: slug("Mitiga", 2024),
    name: "Mitiga",
    year: 2024,
    winner: false,
    description: "Cloud investigation and response automation (CIRA) for SaaS and cloud environments.",
    status: "active",
    category: "Cloud Security",
    founded: 2019,
  },
  {
    id: slug("P0 Security", 2024),
    name: "P0 Security",
    year: 2024,
    winner: false,
    description: "Cloud access governance — just-in-time privileged access for cloud environments.",
    status: "active",
    category: "Identity & Access",
    founded: 2022,
  },
  {
    id: slug("Antimatter", 2024),
    name: "Antimatter",
    year: 2024,
    winner: false,
    description: "Data privacy infrastructure for building privacy-compliant applications.",
    status: "active",
    category: "Privacy & Compliance",
    founded: 2022,
  },
  {
    id: slug("Aembit", 2024),
    name: "Aembit",
    year: 2024,
    winner: false,
    description: "Workload identity and access management — IAM for machine-to-machine communication.",
    status: "active",
    category: "Identity & Access",
    founded: 2021,
  },
  {
    id: slug("RAD Security", 2024),
    name: "RAD Security",
    year: 2024,
    winner: false,
    description: "Cloud-native runtime security using behavioral fingerprints instead of signatures.",
    status: "active",
    category: "Cloud Security",
    founded: 2022,
  },
  {
    id: slug("VulnCheck", 2024),
    name: "VulnCheck",
    year: 2024,
    winner: false,
    description: "Vulnerability intelligence and exploit detection platform.",
    status: "active",
    category: "Vulnerability Management",
    founded: 2022,
  },

  // ===== 2025 =====
  {
    id: slug("ProjectDiscovery", 2025),
    name: "ProjectDiscovery",
    year: 2025,
    winner: true,
    description:
      "Open-source vulnerability detection and security automation platform (Nuclei) for finding and fixing security issues.",
    status: "active",
    category: "Vulnerability Management",
    founded: 2020,
    lessonLearned:
      "Open-source-first security tooling (Nuclei) with massive community adoption. Lesson: building community-driven detection templates created a moat that proprietary scanners can't replicate.",
  },
  {
    id: slug("Aurascape", 2025),
    name: "Aurascape",
    year: 2025,
    winner: false,
    description: "AI security and protection platform for monitoring and securing AI applications.",
    status: "active",
    category: "AI Security",
  },
  {
    id: slug("CalypsoAI", 2025),
    name: "CalypsoAI",
    year: 2025,
    winner: false,
    description: "AI application security at runtime — guardrails for LLM deployments.",
    status: "active",
    category: "AI Security",
  },
  {
    id: slug("Command Zero", 2025),
    name: "Command Zero",
    year: 2025,
    winner: false,
    description: "Autonomous investigations platform using AI agents for security operations.",
    status: "active",
    category: "Security Operations",
  },
  {
    id: slug("EQTY Lab", 2025),
    name: "EQTY Lab AG",
    year: 2025,
    winner: false,
    description: "AI integrity and governance — cryptographic provenance for AI model training and outputs.",
    status: "active",
    category: "AI Security",
  },
  {
    id: slug("Knostic", 2025),
    name: "Knostic",
    year: 2025,
    winner: false,
    description: "LLM access control — need-to-know controls for enterprise AI deployments.",
    status: "active",
    category: "AI Security",
  },
  {
    id: slug("Metalware", 2025),
    name: "Metalware",
    year: 2025,
    winner: false,
    description: "Firmware security and automated fuzzing for embedded systems and IoT devices.",
    status: "active",
    category: "IoT / Hardware Security",
  },
  {
    id: slug("MIND", 2025),
    name: "MIND",
    year: 2025,
    winner: false,
    description: "Data loss prevention and insider risk management with real-time data flow visibility.",
    status: "active",
    category: "Data Security",
  },
  {
    id: slug("Smallstep", 2025),
    name: "Smallstep",
    year: 2025,
    winner: false,
    description: "Device identity and zero-trust infrastructure using automated certificate management.",
    status: "active",
    category: "Identity & Access",
  },
  {
    id: slug("Twine Security", 2025),
    name: "Twine Security",
    year: 2025,
    winner: false,
    description: "AI digital employees (agents) for cybersecurity tasks — autonomous security workforce.",
    status: "active",
    category: "Security Operations",
  },

  // ===== 2026 =====
  {
    id: slug("Charm Security", 2026),
    name: "Charm Security",
    year: 2026,
    winner: false,
    description: "AI-powered social engineering defense.",
    status: "active",
    category: "Threat Detection",
  },
  {
    id: slug("Clearly AI", 2026),
    name: "Clearly AI",
    year: 2026,
    winner: false,
    description: "AI security and explainability platform.",
    status: "active",
    category: "AI Security",
  },
  {
    id: slug("Crash Override", 2026),
    name: "Crash Override",
    year: 2026,
    winner: false,
    description: "Attack surface management and exposure prioritization.",
    status: "active",
    category: "Vulnerability Management",
  },
  {
    id: slug("Fig Security", 2026),
    name: "Fig Security",
    year: 2026,
    winner: false,
    description: "Identity security and access governance.",
    status: "active",
    category: "Identity & Access",
  },
  {
    id: slug("Geordie AI", 2026),
    name: "Geordie AI",
    year: 2026,
    winner: false,
    description: "AI agent security and governance.",
    status: "active",
    category: "AI Security",
  },
  {
    id: slug("Glide Identity", 2026),
    name: "Glide Identity",
    year: 2026,
    winner: false,
    description: "Identity verification using telco network signals.",
    status: "active",
    category: "Identity & Access",
  },
  {
    id: slug("Humanix", 2026),
    name: "Humanix",
    year: 2026,
    winner: false,
    description: "Human-centric cybersecurity with behavioral AI.",
    status: "active",
    category: "Security Operations",
  },
  {
    id: slug("Realm Labs", 2026),
    name: "Realm Labs",
    year: 2026,
    winner: false,
    description: "Security infrastructure for AI agents.",
    status: "active",
    category: "AI Security",
  },
  {
    id: slug("Token Security", 2026),
    name: "Token Security",
    year: 2026,
    winner: false,
    description: "Non-human identity security and machine credential management.",
    status: "active",
    category: "Identity & Access",
  },
  {
    id: slug("ZeroPath", 2026),
    name: "ZeroPath",
    year: 2026,
    winner: false,
    description: "AI-powered application security testing.",
    status: "active",
    category: "Application Security",
  },
];

// Deduplicate companies that appear in multiple years - keep earliest appearance
// but note repeat appearances
export function getUniqueCompanies(): Company[] {
  return companies;
}

export function getYears(): number[] {
  const years = [...new Set(companies.map((c) => c.year))].sort((a, b) => b - a);
  return years;
}

export function getCompanyById(id: string): Company | undefined {
  return companies.find((c) => c.id === id);
}
